### ISSUE TITLE
Images are not created with absRefPrefix

### ISSUE THREAD

**Issue by phpherod** [lochmueller/fl_realurl_image#10]
In all Typo3-Versions the images are not created, when `config.absRefPrefix = example.com` is used.
I never bothered with this in past but now I want to switch to `absRefPrefix` so everything has absolute path.

Error description:
On the page the image path is leading to a picture in the folder `typo3temp/fl_realurl_image/`.
But if I look in the folder `typo3temp/fl_realurl_image/`, the image is not created.

I find out, if I remove the following line in RealUrlImage.php
`return htmlspecialchars($GLOBALS['TSFE']->absRefPrefix) . ltrim($url, '/');`
and add this line
`return $url;`
then it works.
I am just not sure, for what the function `addAbsRefPrefix()` is. Apparantly the string `http://` in `$url` is not found. I dont know where the variable `$url` get the value.
The error is caused mainly because of this line, when `http://` in `$url` is not found:
`return htmlspecialchars($GLOBALS['TSFE']->absRefPrefix) . ltrim($url, '/');`
Could you advise something? Can I just put `return $url;`?Is this a bug? Or do I anything wrong?

**Comment by lochmueller** [comment]
Hey @phpherod . The aconfiguration `config.absRefPrefix = example.com` is wrong. Take a look at https://docs.typo3.org/typo3cms/TyposcriptReference/Setup/Config/Index.html#absrefprefix

It should somthing like `/` or  `http://www.example.com/` oder `/folder/` (always a `/` at the end). Please check the configuration of absRefPrefix first.

Regards,
Tim

**Comment by phpherod** [comment]
Hello, sorry if I wrote just example.com, of course I put http://www.example.com/ but it doesnt work.

**Comment by lochmueller** [comment]
OK. I will check this in the next days...

**Comment by phpherod** [comment]
Hello, is here any update? Is the issue solved?

**Comment by lochmueller** [comment]
Hey @phpherod 
Sorry... but no news on this topic.
Regards,
Tim

**Comment by lochmueller** [comment]
I close this issue. There will be no next version at the moment.
Feel free to send pull requests and I will release a version.
But there is no active development at the moment...
