### ISSUE TITLE
PHP 7 checks - Declaration of ImageViewHelper->render & ImageService->getImageUri

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/fl_realurl_image#11]
PHP 7 checks - Declaration of ImageViewHelper->render & ImageService->getImageUri

**Comment by fritzdacat** [comment]
I Have the same Problem with PHP 7.0.10

Uncaught TYPO3 Exception
#1: PHP Warning: Declaration of FRUIT\FlRealurlImage\Xclass\Fluid\ViewHelpers\ImageViewHelper::render($src = NULL, $width = NULL, $height = NULL, $minWidth = NULL, $minHeight = NULL, $maxWidth = NULL, $maxHeight = NULL, $treatIdAsReference = false, $image = NULL, $crop = NULL) should be compatible with TYPO3\CMS\Fluid\ViewHelpers\ImageViewHelper::render($src = NULL, $width = NULL, $height = NULL, $minWidth = NULL, $minHeight = NULL, $maxWidth = NULL, $maxHeight = NULL, $treatIdAsReference = false, $image = NULL, $crop = NULL, $absolute = false) in /Applications/MAMP/htdocs/xxxx/typo7/web/typo3conf/ext/fl_realurl_image/Classes/Xclass/Fluid/ViewHelpers/ImageViewHelper.php line 67

**Comment by fritzdacat** [comment]
Sorry, i don't see this Issue: https://github.com/lochmueller/fl_realurl_image/issues/5

**Comment by lochmueller** [comment]
Part of the next release....
