### ISSUE TITLE
"Enlarge on Click" links to original filename

### ISSUE THREAD

**Issue by MrGecco** [lochmueller/fl_realurl_image#19]
If "Enlarge on Click" is activated in a textmedia content element the link **points at the original filename** and not at the RealURL Image Name.

Example:
- Original Filename: notseofriendlyname.jpg
- RealURL Image Name: seofriendly.jpg

HTML-Output:
```
<div class="ce-media">
	<a href="typo3temp/fl_realurl_image/notseofriendlyname-8a.jpg" data-lightbox="1">
		<img src="typo3temp/fl_realurl_image/seofriendly-48.jpg" alt="" width="299" height="200">
	</a>
</div>
```

Further information:
- However, the thumbnail is generated and stored with the RealURL Image Name, the full image is stored with the original file name.
- Typo3 v7.6.15

Best regards

**Comment by MrGecco** [comment]
Hey. Any updates regarding this issue? Thank you very much

**Comment by lochmueller** [comment]
@MrGecco sorry... but no news on that topic. I will check this in my next OpenSource Sprint... but this will take a few days/weeks...

**Comment by MrGecco** [comment]
@lochmueller thank you for the answer and your effort :+1:

**Comment by Andreas-Sommer** [comment]
Same issue here 
fl_realurl_image 5.0.0
typo3 8.7.15

**Comment by lochmueller** [comment]
I close this issue. There will be no next version at the moment.
Feel free to send pull requests and I will release a version.
But there is no active development at the moment...
