### ISSUE TITLE
Can not add Image in TYPO3 8.6

### ISSUE THREAD

**Issue by DonRagout** [lochmueller/fl_realurl_image#20]
When i try do add an Image to a TYPO3 content element "Image" i get a "500 internal server error". The Log says

`Argument "src" has already been defined, thus it should not be defined again. | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file typo3_src-8.6.1/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 169. Requested URL: https://example.com/typo3/index.php?ajaxID=%2Fajax%2Frecord%2Finline%2Fcreate&ajaxToken=ebd3b9e94d7d9c8be3a3083ecc18d3d8e6a563ec`

**Comment by celmedia** [comment]
the same here.. also 8.6.1 :-(

**Comment by lochmueller** [comment]
Close this one. Here is a general Issue to this topic: https://github.com/lochmueller/fl_realurl_image/issues/21
