### ISSUE TITLE
Check 8.7.x compatibility

### ISSUE THREAD

**Issue by lochmueller** [lochmueller/fl_realurl_image#21]
- Check 8.7.x compatibility

> Argument "src" has already been defined, thus it should not be defined again

**Comment by ingeniumdesign** [comment]
**same here:** TYPO3 8.7.8

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1253036401: Argument "src" has already been defined, thus it should not be defined again. | TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file /html/source/typo3_src-8.7.8/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 169. Requested URL: https://www.domain.de/index.php?id=25

**Comment by mo-mueller** [comment]
I still have this problem on a custom content element, which I have created with the Mask Extension. I have used this code for an image:

`<f:image image="{data_item.tx_mask_column_icon.0}" id="col_{key}_icon" alt="{data_item.tx_mask_column_icon.0.alternative}" width="111"/>`

And I'm getting this error:

> Argument "src" has already been defined, thus it should not be defined again. 

Must I change something on my code or is that related to your extension?

**Comment by lochmueller** [comment]
Already fixed in current master. Release will follow soon

**Comment by meeust** [comment]
Is it possible to reopen this case?
I have this problem too.
Is it now fixed.
Typo3 8.7.18
fl_realurl_image 4.1.4
Extension installed, static template set, no TS in setup.
Can it be that there is a conflict of the extension with Title / Old Tag or Caption?

**Comment by lochmueller** [comment]
"Extension installed, static template set, no TS in setup." Sound like other problems?!?!
" Can it be that there is a conflict of the extension with Title / Old Tag or Caption?" I dont know what you mean in detail. Please create a new issue and attach some more details (perhaps screenshots etc.).
Regards,
Tim

**Comment by meeust** [comment]
Hello Tim,
I have no problem without the installation of fl_realurl_image.
After installation I get the following error:

Oops, an error occurred!
Argument "src" has already been defined, thus it should not be defined again.
More information ...

At first it seemed like only some pages (all with content text / image)
affected. Therefore, I compared whether the contents differed in terms of title / alt and caption. That should be the only difference between the records. But I have found no connection.
(Therefore, the note in the previous post came to Title / Alt and Caption)
Now I only have errors. But sometimes the above and sometimes server error 500.
see.
http://webspace-online.webseiten.cc/error.jpg
http://webspace-online.webseiten.cc/error500.jpg

Typo3 8.7.18
fl_realurl_image 4.1.4
php 7.0.24
No extra Setup or Constants for the Extension (only include in Roottemplate as static Template)

Between installation and deinstallation I always empty the cache via InstallTool.

Sometimes I get the error argument "src" has alread .. when I try to open the page content.
Sometimes the page content is opened but when I go to the image tab the Error 500 comes up and the tab does not open.

After the uninstall everything is ok again.
Regards, 
Markus

**Comment by lochmueller** [comment]
But I also write in the comment before: "Already fixed in current master. Release will follow soon"

This fix https://github.com/lochmueller/fl_realurl_image/commit/54e45507ae9142377c38533baf12b0c49406758d is not part of the 4.1.4 release. Please try the current master.

**Comment by meeust** [comment]
Hello Tim,
Sorry I had the term "Master" misunderstood and understood it so that the patch is already integrated Thank you
Regards,
Markus
