### ISSUE TITLE
This extension is not compatible with php7

### ISSUE THREAD

**Issue by davidzach** [lochmueller/fl_realurl_image#5]
#1: PHP Warning: Declaration of FRUIT\FlRealurlImage\Xclass\UriImageViewHelper::render($src = NULL, $image = NULL, $width = NULL, $height = NULL, $minWidth = NULL, $minHeight = NULL, $maxWidth = NULL, $maxHeight = NULL, $treatIdAsReference = false) should be compatible with TYPO3\CMS\Fluid\ViewHelpers\Uri\ImageViewHelper::render($src = NULL, $image = NULL, $width = NULL, $height = NULL, $minWidth = NULL, $minHeight = NULL, $maxWidth = NULL, $maxHeight = NULL, $treatIdAsReference = false, $crop = NULL, $absolute = false) in ..\typo3conf\ext\fl_realurl_image\Classes\Xclass\UriImageViewHelper.php line 18

**Comment by lochmueller** [comment]
I will add "$crop = NULL, $absolute = false" in the next release to fit the new TYPO3 decleration...

**Comment by fritzdacat** [comment]
When will the next release come?

**Comment by lochmueller** [comment]
I don't know... after the next community sprint (I think in november) or after the next sponsorship.

**Comment by lochmueller** [comment]
Next release in a few minutes... clos this issue.
