### ISSUE TITLE
Installation with Composer failed

### ISSUE THREAD

**Issue by sebastianschrama** [lochmueller/fl_realurl_image#8]
When I try to install the extension via composer with `composer require typo3-ter/fl-realurl-image` I get the following error message:

**Installation failed, reverting ./composer.json to its original content.
[ErrorException]
Undefined index: 113adfdc**

**Comment by fritzdacat** [comment]
I have thesame Problem with ""typo3-ter/fl_realurl_image": "4.0.1""

I use: 

"type": "vcs",
"url": "https://github.com/lochmueller/fl_realurl_image.git"

an then ""lochmueller/fl_realurl_image": "4.0.1"" in composer.json

that's works fine

**Comment by lochmueller** [comment]
Do you try also "lochmueller/fl_realurl_image" as Package?

**Comment by fritzdacat** [comment]
"lochmueller/fl_realurl_image" from TYPO3 TER?

It have loaded from "https://github.com/lochmueller/fl_realurl_image.git" via Composer

**Comment by lochmueller** [comment]
composer.typo3.org is just a temporary solution to deliver the packages that are not "really composer" based. All my extensions are on Packagist, so it is recommended to use the real Packagist key and not the temporary key of composer.typo3.org.

**Comment by lochmueller** [comment]
Update new version... please use https://packagist.org/packages/lochmueller/fl_realurl_image
Issue closed...
