### ISSUE TITLE
Double slash with IMAGE and layoutKey

### ISSUE THREAD

**Issue by ghost** [lochmueller/fl_realurl_image#9]
Images generated with a TS IMAGE object and a layoutKey definition get a double slash prepended to the url.

PHP 5.6
TYPO3 7.6.9
EXT:fl_realurl_image 4.0.1
config.absRefPrefix = /

**Comment by lochmueller** [comment]
Close this issue. Current version 5.0.0 is only valid for TYPO3 CMS 8.7.
Please update to the current version and recheck this. If the problem still exists I will reopen the task.
